/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JFrame;

/**
 *
 * @author VAMPIRE
 */
public class MainFrame extends javax.swing.JFrame {

    String FN,LN,email,pass,ConPass,Phone;
    Regex R=new Regex();
    boolean flagFN, flagLN, flagEmail, flagPh, flagPass, flagCPass,FlagGen;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
          Male_Radio.setSelected(true);
          Female_Radio.setBackground(new Color(78, 78, 79));
          Male_Radio.setBackground(new Color(78, 78, 79));
          FirstName.setForeground(Color.WHITE);
          LastName.setForeground(Color.WHITE);
          Email.setForeground(Color.WHITE);
          Gender.setForeground(Color.WHITE);
          Male_Radio.setForeground(Color.WHITE);
          Female_Radio.setForeground(Color.WHITE);
          PhoneNumber.setForeground(Color.WHITE);
          Password.setForeground(Color.WHITE);
          ConfirmPassword.setForeground(Color.WHITE);
          Submit.setForeground(Color.WHITE);
          Clear_Button.setForeground(Color.WHITE);
          Exit.setForeground(Color.WHITE);
          Password_msg.setForeground(Color.WHITE);
          
          FirstName_Label.setForeground(Color.RED);
          LastName_Label.setForeground(Color.RED);
          Email_Label.setForeground(Color.RED);
          PhoneNumber_Label.setForeground(Color.RED);
          Password_Label.setForeground(Color.RED);
          ConfirmPassword_Label.setForeground(Color.RED);
          Gender_Label.setForeground(Color.RED);
          Successful.setForeground(Color.GREEN);
          
          ButtonGroup gender=new ButtonGroup();
          gender.add(Male_Radio);
          gender.add(Female_Radio);
          
          Male_Radio.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        FirstName_TextField = new javax.swing.JTextField();
        LastName_TextField = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JLabel();
        Email_TextField = new javax.swing.JTextField();
        Password_PasswordField = new javax.swing.JPasswordField();
        ConfirmPassword_PasswordField = new javax.swing.JPasswordField();
        Submit = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        FirstName_Label = new javax.swing.JLabel();
        LastName_Label = new javax.swing.JLabel();
        Email_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        ConfirmPassword_Label = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        PhoneNumber_TextField = new javax.swing.JTextField();
        PhoneNumber_Label = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Gender_Label = new javax.swing.JLabel();
        Password_msg = new javax.swing.JLabel();
        Successful = new javax.swing.JLabel();
        Clear_Button = new javax.swing.JButton();
        SignupForm = new javax.swing.JLabel();
        Male_Radio = new javax.swing.JRadioButton();
        Female_Radio = new javax.swing.JRadioButton();

        jLabel7.setText("jLabel7");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FirstName.setText("First Name");

        LastName.setText("Last Name");

        FirstName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName_TextFieldActionPerformed(evt);
            }
        });

        LastName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastName_TextFieldActionPerformed(evt);
            }
        });

        Email.setText("Email ");

        Password.setText("Password");

        ConfirmPassword.setText("Confirm Password");

        Email_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_TextFieldActionPerformed(evt);
            }
        });

        Password_PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_PasswordFieldActionPerformed(evt);
            }
        });

        ConfirmPassword_PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPassword_PasswordFieldActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(102, 153, 255));
        Submit.setText("Submit");
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(102, 153, 255));
        Exit.setText("Exit");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        PhoneNumber.setText("Phone Number");

        Gender.setText("Gender");

        Password_msg.setText("   Password Must Have Lenght of Atleast 8 Characters, Atleast 1 Uppercase Letter,1 Lowercase Letter and 1 Digit ");

        Successful.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Clear_Button.setBackground(new java.awt.Color(102, 153, 255));
        Clear_Button.setText("Clear All");
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        SignupForm.setBackground(new java.awt.Color(102, 153, 255));
        SignupForm.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SignupForm.setForeground(new java.awt.Color(255, 255, 255));
        SignupForm.setText("                                      Signup Form");
        SignupForm.setOpaque(true);

        Male_Radio.setText("Male");

        Female_Radio.setText("Female");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password_msg)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LastName)
                                            .addComponent(FirstName)
                                            .addComponent(PhoneNumber)))
                                    .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Gender, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPassword)
                                    .addComponent(Password))
                                .addGap(33, 33, 33)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(FirstName_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(FirstName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Male_Radio)
                                            .addGap(42, 42, 42)
                                            .addComponent(Female_Radio)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(PhoneNumber_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                            .addComponent(LastName_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                            .addComponent(Email_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Email_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LastName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PhoneNumber_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Password_PasswordField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ConfirmPassword_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ConfirmPassword_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(Gender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Successful, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(Clear_Button)
                .addGap(28, 28, 28)
                .addComponent(Submit)
                .addGap(28, 28, 28)
                .addComponent(Exit)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignupForm, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FirstName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LastName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LastName))
                    .addComponent(LastName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneNumber)
                    .addComponent(PhoneNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gender_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Male_Radio)
                        .addComponent(Gender))
                    .addComponent(Female_Radio))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Email_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Email)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Password))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConfirmPassword_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ConfirmPassword))
                    .addComponent(ConfirmPassword_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Successful, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Exit)
                        .addComponent(Submit)
                        .addComponent(Clear_Button)))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName_TextFieldActionPerformed
        
    }//GEN-LAST:event_FirstName_TextFieldActionPerformed

    private void LastName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastName_TextFieldActionPerformed

    private void Email_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_TextFieldActionPerformed

    private void Password_PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_PasswordFieldActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        
        boolean b,b1,b2;
        FN=FirstName_TextField.getText();
        LN=LastName_TextField.getText();
        email=Email_TextField.getText();
        pass=Password_PasswordField.getText();
        ConPass=ConfirmPassword_PasswordField.getText();
        Phone=PhoneNumber_TextField.getText();
        /*if(Male_CheckBox.isSelected()==true&&Female_CheckBox.isSelected()==true)
        {
            Gender_Label.setText("Select Only One Box");
            FlagGen=false;
        }
        else
        {
            FlagGen=true;
        }*/
        
        if((R.RegexForEmail(email))==false)
        {
          Email_Label.setText("Invalid");
          flagEmail=false;  
        }
        else
        {
            flagEmail = true;
        }
        if((R.RegexForName(FN))==false)
        {
          FirstName_Label.setText("Invalid");
          flagFN=false; 
        }
        else
        {
            flagFN = true;
        }
        if((R.RegexForName(LN))==false)
        {
          LastName_Label.setText("Invalid");
          flagLN=false;  
        }
        else
        {
            flagLN = true;
        }
        if((R.RegexForPassword(pass))==false)
        {
            Password_Label.setText("Invalid Password");
            flagPass=false;
        }
        else
        {
            flagPass = true;
        }
        if(!pass.equals(ConPass))
        {
         ConfirmPassword_Label.setText("Invalid!, Password not matched");
         flagCPass=false;
        }
        else
        {
            flagCPass = true;
        }
        if((R.RegexForPhone(Phone))==false)
        {
            PhoneNumber_Label.setText("Invalid");
            flagPh=false;   
        }
        else
        {
            flagPh = true;
        }
        if(flagFN)
        {
            FirstName_Label.setText("");
        }
        if(flagLN) 
        {
            LastName_Label.setText("");
        }
        if(flagEmail)
        {
            Email_Label.setText("");
        }
        if(flagPh)
        {
           PhoneNumber_Label.setText("");
        }
        if(flagPass)
        {
           Password_Label.setText("");
        }
        if(flagCPass)
        {
           ConfirmPassword_Label.setText("");
        }
        if(FlagGen)
        {
            Gender_Label.setText("");
        }
        if(flagFN && flagLN && flagEmail && flagPh && flagPass && flagCPass)
        {  
            Submit.hide();
            Successful.setText("Signup Successfull!");
        }
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        
        System.exit(1);
        
    }//GEN-LAST:event_ExitActionPerformed

    private void ConfirmPassword_PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPassword_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPassword_PasswordFieldActionPerformed

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
       
          FirstName_Label.setText("");
          LastName_Label.setText("");
          Email_Label.setText("");
          //Male_CheckBox.setSelected(false);
          //Female_CheckBox.setSelected(false);
          PhoneNumber_Label.setText("");
          Password_Label.setText("");
          ConfirmPassword_Label.setText("");
          Gender_Label.setText("");
          
          FirstName_TextField.setText("");
          LastName_TextField.setText("");
          Email_TextField.setText("");
          PhoneNumber_TextField.setText("");
          Password_PasswordField.setText("");
          ConfirmPassword_PasswordField.setText("");
          
          Successful.setText("");
          Submit.setVisible(true);
       
    }//GEN-LAST:event_Clear_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame=new MainFrame();
                frame.setTitle("Signup Form");
                frame.getContentPane().setBackground(new java.awt.Color(78, 78, 79));
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_Button;
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JLabel ConfirmPassword_Label;
    private javax.swing.JPasswordField ConfirmPassword_PasswordField;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JButton Exit;
    private javax.swing.JRadioButton Female_Radio;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel FirstName_Label;
    private javax.swing.JTextField FirstName_TextField;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Gender_Label;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastName_Label;
    private javax.swing.JTextField LastName_TextField;
    private javax.swing.JRadioButton Male_Radio;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JPasswordField Password_PasswordField;
    private javax.swing.JLabel Password_msg;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel PhoneNumber_Label;
    private javax.swing.JTextField PhoneNumber_TextField;
    private javax.swing.JLabel SignupForm;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Successful;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
 }
